- Create drawer menu
GVR-Secure-Solutions/lekkalu-app pull request #2
Opened 2023-11-02 17:00 UTC by Parthshiroya06

Create drawer menu and inside of two screen 
- Home
- Setting

2023-11-02 18:53 UTC, rockingrohit9639 requested changes
Please add the `Drawer` navigation in root `_layout` and remove other unnecessary code.

2023-11-02 18:53 UTC, rockingrohit9639 commented on app/(drawer)/home/index.tsx
> +})
We are using `Native Base` so you can ignore creating the stylesheet and you can give props to component itself.

so import `View` from `native-base` and inject the styling that component

2023-11-02 18:53 UTC, rockingrohit9639 commented on app/login.tsx
> +          {/* <Text>Hellosd</Text> */}
Remove this unnecessary comment. And please try avoiding them next time.

2023-11-03 16:57 UTC, Parthshiroya06 commented on app/login.tsx
> +          {/* <Text>Hellosd</Text> */}
Hello,

I have to  apply your suggestion & create PR

2023-11-04 15:23 UTC, rockingrohit9639 approved these changes

2023-11-04 15:23 UTC, merged