Feature/income statement 17
GVR-Secure-Solutions/lekkalu-app pull request #36
Opened 2024-01-26 15:24 UTC by Snehal018

2024-01-29 03:10 UTC, bharathkumarchowdary requested changes
- [ ] In IncomeExpense type only salary is shown, there are 2 more. 
        PERSONAL = 'Personal', gettext_lazy('Personal')
        LOAN_REPAYMENT = 'Loan_repayment', gettext_lazy('Loan_repayment')
        INVESTMENT = 'Investment', gettext_lazy('Investment')

- [ ] When there is no object in Income or Expense, not good to show NaN%, it is visually not appealing
- [ ] Now it is only possible to add Income, what about expenses? How can I add Expenses?

2024-01-30 19:02 UTC, mohitkhatri06 approved these changes

2024-02-05 18:32 UTC, mohitkhatri06 submitted a review, later dismissed

2024-02-06 02:38 UTC, bharathkumarchowdary submitted a review, later dismissed

2024-02-07 04:16 UTC, mohitkhatri06 approved these changes

2024-02-07 05:20 UTC, merged