design settings ui, integrate settings page api
GVR-Secure-Solutions/lekkalu-app pull request #41
Opened 2024-01-28 18:16 UTC by Snehal018

2024-01-29 03:00 UTC, bharathkumarchowdary requested changes
- [ ] In reset password page, it is better to fetch the user's email ID from backend and keep it in textbox instead of leaving it blank

![image](https://github.com/GVR-Secure-Solutions/lekkalu-app/assets/8872935/95f7828d-8da1-4cc0-8b99-693bb7e6277f)

- [ ] Open mail app button not working

2024-01-29 14:10 UTC, mohitkhatri06 commented on schema/settings.ts
> +  username: z.string().min(3, 'Please enter at least 3 characters!').max(150, 'Please enter at most 150 characters!'),
in the frontend this field we had minimum 6 chars

2024-01-30 05:36 UTC, mohitkhatri06 approved these changes

2024-02-04 05:57 UTC, bharathkumarchowdary requested changes
email verification flow is following reset password flow. why? also why is it not loading the user's email? why does the user have to re-enter email id?

2024-02-04 05:58 UTC, bharathkumarchowdary commented
@Snehal018 , Please mask reset password for now, we'll re-enable it in future

2024-02-04 16:44 UTC, Snehal018 commented
@bharathkumarchowdary , do i only need to disable reset password or both reset and forgot password ?

2024-02-04 17:10 UTC, bharathkumarchowdary commented
> @bharathkumarchowdary , do i only need to disable reset password or both reset and forgot password ?

both

2024-02-05 12:47 UTC, bharathkumarchowdary commented
@Snehal018 , email verification is still not loading user's email and keeping the field blank

2024-02-05 12:50 UTC, bharathkumarchowdary commented
> email verification flow is following reset password flow. why? also why is it not loading the user's email? why does the user have to re-enter email id?

2024-02-07 15:50 UTC, mohitkhatri06 approved these changes

2024-02-08 04:28 UTC, bharathkumarchowdary commented
I'm getting the following error 

> ⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: The following Swift pods cannot yet be integrated as static libraries:
> The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
> The Swift pod `FirebaseSessions` depends upon `FirebaseCore`, `FirebaseCoreExtension`, `FirebaseInstallations`, `GoogleDataTransport`, `GoogleUtilities`, and `nanopb`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

2024-02-08 04:32 UTC, Snehal018 commented
@bharathkumarchowdary , why are you installing pods ? since we are using expo we should not install pods as its native thing to do not the expo way

2024-02-09 12:02 UTC, bharathkumarchowdary commented
I'm not able to login
![image](https://github.com/GVR-Secure-Solutions/lekkalu-app/assets/8872935/16789a86-c635-4568-b5bd-d24ea1420507)

2024-02-09 12:05 UTC, mohitkhatri06 commented
> I'm not able to login ![image](https://private-user-images.githubusercontent.com/8872935/303644104-16789a86-c635-4568-b5bd-d24ea1420507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODA1NjEsIm5iZiI6MTcwNzQ4MDI2MSwicGF0aCI6Ii84ODcyOTM1LzMwMzY0NDEwNC0xNjc4OWE4Ni1jNjM1LTQ1NjgtYjViZC1kMjRlYTE0MjA1MDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMTIwNDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBkODE4OTY5YTY5NWYyZjdiOGI0OGVjZDE4NTlhMTJmM2FjYjFhYTcwYzkzMWNmYjViMmU0ZGViMzk1NTZiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KxVR4Ju6Kso7dZiUpbGYySoU1PxvRI7iMgd4tyyblkU)

@bharathkumarchowdary did you checked that in the poject it is ".env" instead of ".env.example"

2024-02-09 12:07 UTC, bharathkumarchowdary commented
@mohitkhatri06 , yes it is so!

2024-02-10 19:05 UTC, bharathkumarchowdary requested changes
1. Even when there is no goal in user's account, it shows some on track, off track cards 
![image](https://github.com/GVR-Secure-Solutions/lekkalu-app/assets/8872935/19e89f6a-b8c2-4812-aaba-6379c149a36b)

2. Why is KPI hardcoded single choice?
3. I'm not able to add income expense item from income statement. without that, we can't test goals
4. Completion date might be confusing. Change the name to Target Date or Target to Accomplish or Accomplish goal by or Target Completion Date. Is this the same as target_date in API?

2024-02-10 19:16 UTC, bharathkumarchowdary commented
In PR 45, the latest PR, there is no error, but in this PR, I'm consistently seeing that it shows this error. I don't know why and I can't debug

> /opt/homebrew/bin/npm run ios
lekkalu-app@1.0.0 ios
 expo start --ios
(node:63941) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Starting project at /Users/bharathkumargundala/code/lekkalu-app
env: load .env
env: export EXPO_PUBLIC_TOKEN_BASE_URL EXPO_PUBLIC_USER_BASE_URL EXPO_PUBLIC_API_BASE_URL EXPO_PUBLIC_API_V2_BASE_URL
Experimental path aliases feature is enabled. Learn more: https://docs.expo.dev/guides/typescript/#path-aliases
Starting Metro Bundler
CommandError: No development build (com.lekkalu.finuncle) for this project is installed. Please make and install a development build on the device first.
Learn more: https://docs.expo.dev/development/build/

2024-02-11 12:33 UTC, Snehal018 commented
> 1. Even when there is no goal in user's account, it shows some on track, off track cards
>    ![image](https://private-user-images.githubusercontent.com/8872935/303859401-19e89f6a-b8c2-4812-aaba-6379c149a36b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTQ5MjEsIm5iZiI6MTcwNzY1NDYyMSwicGF0aCI6Ii84ODcyOTM1LzMwMzg1OTQwMS0xOWU4OWY2YS1iOGMyLTQ4MTItYWFiYS02Mzc5YzE0OWEzNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMTIzMDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWYxYmQ1YmQyNWFmYzJhYzkxNmFkYTBlZDJmOGI3MGMwNjM3NWJhMzkyNTk3OGM3MTNlZWZkZDE4OThkZjgwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BLQVL7X7K6B4JoSJUWmqF6cAIFudtBK7QFy2tLkrxJ0)
> 2. Why is KPI hardcoded single choice?
> 3. I'm not able to add income expense item from income statement. without that, we can't test goals
> 4. Completion date might be confusing. Change the name to Target Date or Target to Accomplish or Accomplish goal by or Target Completion Date. Is this the same as target_date in API?

@bharathkumarchowdary, why is this PR used to test the goal feature when there is a dedicated goals PR where the feature is completely integrated? The only required change here is the name change of completion date

2024-02-11 15:31 UTC, bharathkumarchowdary commented
> > 1. Even when there is no goal in user's account, it shows some on track, off track cards
> >    ![image](https://private-user-images.githubusercontent.com/8872935/303859401-19e89f6a-b8c2-4812-aaba-6379c149a36b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTQ5MjEsIm5iZiI6MTcwNzY1NDYyMSwicGF0aCI6Ii84ODcyOTM1LzMwMzg1OTQwMS0xOWU4OWY2YS1iOGMyLTQ4MTItYWFiYS02Mzc5YzE0OWEzNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMTIzMDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWYxYmQ1YmQyNWFmYzJhYzkxNmFkYTBlZDJmOGI3MGMwNjM3NWJhMzkyNTk3OGM3MTNlZWZkZDE4OThkZjgwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BLQVL7X7K6B4JoSJUWmqF6cAIFudtBK7QFy2tLkrxJ0)
> > 2. Why is KPI hardcoded single choice?
> > 3. I'm not able to add income expense item from income statement. without that, we can't test goals
> > 4. Completion date might be confusing. Change the name to Target Date or Target to Accomplish or Accomplish goal by or Target Completion Date. Is this the same as target_date in API?
> 
> @bharathkumarchowdary, why is this PR used to test the goal feature when there is a dedicated goals PR where the feature is completely integrated? The only required change here is the name change of completion date

@Snehal018 , Yes it's a mistake, please don't consider [this](https://github.com/GVR-Secure-Solutions/lekkalu-app/pull/41#pullrequestreview-1873980302) comment for this PR. [This](https://github.com/GVR-Secure-Solutions/lekkalu-app/pull/41#issuecomment-1937099766) is the relevant comment

2024-02-11 15:44 UTC, Snehal018 commented
> In PR 45, the latest PR, there is no error, but in this PR, I'm consistently seeing that it shows this error. I don't know why and I can't debug
> 
> > /opt/homebrew/bin/npm run ios
> > lekkalu-app@1.0.0 ios
> > expo start --ios
> > (node:63941) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> > (Use `node --trace-deprecation ...` to show where the warning was created)
> > Starting project at /Users/bharathkumargundala/code/lekkalu-app
> > env: load .env
> > env: export EXPO_PUBLIC_TOKEN_BASE_URL EXPO_PUBLIC_USER_BASE_URL EXPO_PUBLIC_API_BASE_URL EXPO_PUBLIC_API_V2_BASE_URL
> > Experimental path aliases feature is enabled. Learn more: https://docs.expo.dev/guides/typescript/#path-aliases
> > Starting Metro Bundler
> > CommandError: No development build (com.lekkalu.finuncle) for this project is installed. Please make and install a development build on the device first.
> > Learn more: https://docs.expo.dev/development/build/

this is an issue with the development build not being installed in the simulator

2024-02-11 15:58 UTC, bharathkumarchowdary commented
> > In PR 45, the latest PR, there is no error, but in this PR, I'm consistently seeing that it shows this error. I don't know why and I can't debug
> > > /opt/homebrew/bin/npm run ios
> > > lekkalu-app@1.0.0 ios
> > > expo start --ios
> > > (node:63941) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> > > (Use `node --trace-deprecation ...` to show where the warning was created)
> > > Starting project at /Users/bharathkumargundala/code/lekkalu-app
> > > env: load .env
> > > env: export EXPO_PUBLIC_TOKEN_BASE_URL EXPO_PUBLIC_USER_BASE_URL EXPO_PUBLIC_API_BASE_URL EXPO_PUBLIC_API_V2_BASE_URL
> > > Experimental path aliases feature is enabled. Learn more: https://docs.expo.dev/guides/typescript/#path-aliases
> > > Starting Metro Bundler
> > > CommandError: No development build (com.lekkalu.finuncle) for this project is installed. Please make and install a development build on the device first.
> > > Learn more: https://docs.expo.dev/development/build/
> 
> this is an issue with the development build not being installed in the simulator

@Snehal018 , If that is so, why is it working in one PR and not in another? Don't you think the problem might be in the way we mention package dependencies in git commit?

2024-02-11 16:07 UTC, Snehal018 commented
> > > In PR 45, the latest PR, there is no error, but in this PR, I'm consistently seeing that it shows this error. I don't know why and I can't debug
> > > > /opt/homebrew/bin/npm run ios
> > > > lekkalu-app@1.0.0 ios
> > > > expo start --ios
> > > > (node:63941) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> > > > (Use `node --trace-deprecation ...` to show where the warning was created)
> > > > Starting project at /Users/bharathkumargundala/code/lekkalu-app
> > > > env: load .env
> > > > env: export EXPO_PUBLIC_TOKEN_BASE_URL EXPO_PUBLIC_USER_BASE_URL EXPO_PUBLIC_API_BASE_URL EXPO_PUBLIC_API_V2_BASE_URL
> > > > Experimental path aliases feature is enabled. Learn more: https://docs.expo.dev/guides/typescript/#path-aliases
> > > > Starting Metro Bundler
> > > > CommandError: No development build (com.lekkalu.finuncle) for this project is installed. Please make and install a development build on the device first.
> > > > Learn more: https://docs.expo.dev/development/build/
> > 
> > 
> > this is an issue with the development build not being installed in the simulator
> 
> @Snehal018 , If that is so, why is it working in one PR and not in another? Don't you think the problem might be in the way we mention package dependencies in git commit?

@bharathkumarchowdary, technically if you can run the 45 PR, then you should be able to run this PR as well, can you write steps on how are you running the app?

2024-02-15 02:27 UTC, bharathkumarchowdary submitted a review, later dismissed

2024-02-15 07:38 UTC, bharathkumarchowdary approved these changes

2024-02-15 14:08 UTC, mohitkhatri06 approved these changes

2024-02-29 13:56 UTC, closed without merging